[package]
name = "cratetorrent"
version = "1.0.0-alpha.1"
authors = ["mandreyel <mandreyel@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.17"
bytes = "0.5"
chashmap = "2.2"
futures = "0.3"
hex = "0.4"
log = "0.4"
nix = "0.17"
serde = "1.0"
serde_bencode = "0.2"
serde_bytes = "0.11"
serde_derive = "1.0"
sha-1 = "0.8"
# TODO(#54): specify exact features to use to cut down build times
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.2", features = ["codec"] }

[dev-dependencies]
criterion = "0.3"
lazy_static = "1.4"

[[bench]]
name = "iovecs"
harness = false
